// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKw49upWJuPiDBXURry8JiFhEpMktweH0',
    appId: '1:540427680268:web:f3e91ec95a472c28908c29',
    messagingSenderId: '540427680268',
    projectId: 'botellas-3c5c2',
    authDomain: 'botellas-3c5c2.firebaseapp.com',
    storageBucket: 'botellas-3c5c2.firebasestorage.app',
    measurementId: 'G-FMXZYY6YDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPElPJqT0eYZRE0JHV5dwD_ImtT_4qIZQ',
    appId: '1:540427680268:android:c83af19d1507531f908c29',
    messagingSenderId: '540427680268',
    projectId: 'botellas-3c5c2',
    storageBucket: 'botellas-3c5c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2JmKfnaC4DGzwjUxfDZL61JV8AMl8G1I',
    appId: '1:540427680268:ios:679ac8e68c71dda3908c29',
    messagingSenderId: '540427680268',
    projectId: 'botellas-3c5c2',
    storageBucket: 'botellas-3c5c2.firebasestorage.app',
    iosBundleId: 'com.example.botellas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2JmKfnaC4DGzwjUxfDZL61JV8AMl8G1I',
    appId: '1:540427680268:ios:679ac8e68c71dda3908c29',
    messagingSenderId: '540427680268',
    projectId: 'botellas-3c5c2',
    storageBucket: 'botellas-3c5c2.firebasestorage.app',
    iosBundleId: 'com.example.botellas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKw49upWJuPiDBXURry8JiFhEpMktweH0',
    appId: '1:540427680268:web:84c8eff765c57348908c29',
    messagingSenderId: '540427680268',
    projectId: 'botellas-3c5c2',
    authDomain: 'botellas-3c5c2.firebaseapp.com',
    storageBucket: 'botellas-3c5c2.firebasestorage.app',
    measurementId: 'G-3XMN84VKCK',
  );
}
